#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 24 21:49:34 2020
分段线性变化
@author: hou
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

#读取原始图像
img = cv2.imread('t2.jpg')
 
#图像灰度转换
grayImage = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
 
#获取图像高度和宽度
height = grayImage.shape[0]
width = grayImage.shape[1]
 
#创建一幅图像
result = np.zeros((height, width), np.uint8)
 
#图像灰度反色变换 s=255-r
for i in range(height):
    for j in range(width):
        gray = grayImage[i,j]
        if gray<95.625:
            result[i,j] = np.uint8((1/3)*gray)
        elif gray>=95.625 and gray<159.375:
            result[i,j] = np.uint8(31.875+(gray-95.625)*3)
        else:
            result[i,j] = np.uint8(223.125+(gray-159.375)*(1/3))
#显示图像
 
cv2.imshow("Gray Image", grayImage)
cv2.imshow("Result", result)
 

cv2.imwrite("./a3.jpg", result, [int(cv2.IMWRITE_JPEG_QUALITY), 100]) 
#等待显示
cv2.waitKey(0)
cv2.destroyAllWindows()

