#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov 24 22:21:50 2020
对数变换
@author: hou
"""

import numpy as np
import matplotlib.pyplot as plt
import cv2

#对数变换
def log(c, img):
    output = c * np.log(1+ img)
    output=np.rint(output)
    output = np.uint8(output)
    return output

#读取原始图像
img = cv2.imread('t3.jpg')
 
#图像灰度对数变换
output = log(30, img)

#显示图像
cv2.imshow('Input', img)
cv2.imshow('Output', output)
cv2.imwrite("./td.jpg", output, [int(cv2.IMWRITE_JPEG_QUALITY), 100]) 


cv2.waitKey(0)
cv2.destroyAllWindows()